openapi: 3.0.3
info:
  version: 1.0.0
  title: Java Lens Visualizer

paths: {}

components:
  schemas:
    InstrumentedEvents:
      type: object
      required:
        - events
        - sink
      properties:
        sink:
          $ref: '#/components/schemas/SinkConfiguration'
        events:
          type: array
          items:
            $ref: '#/components/schemas/EventFlowDefinition'
    EventFlowDefinition:
      type: object
      required:
        - eventName
        - eventStart
        - eventEnd
      properties:
        eventName:
          type: string
          description: The name of the event
        eventStart:
          $ref: '#/components/schemas/EventCriteria'
        eventEnd:
          $ref: '#/components/schemas/EventCriteria'
    EventCriteria:
      type: object
      required:
        - objectType
      discriminator:
        propertyName: objectType
      properties:
        objectType:
          type: string
    MethodCriteria:
      allOf:
        - $ref: '#/components/schemas/EventCriteria'
      type: object
      required:
        - methodClass
        - methodName
        - eventType
      properties:
        methodClass:
          type: string
        methodName:
          type: string
        eventType:
          type: string
          enum:
            - START
            - END
        threadMatchPattern:
          type: string
        arguments:
          type: array
          items:
            $ref: '#/components/schemas/MethodArgumentCriteria'
        traceArguments:
          type: array
          description: Arguments that will be used to identify and correlate the overall traced flow containing multiple events.
          items:
            $ref: '#/components/schemas/MethodArgument'
        eventArguments:
          type: array
          description: Arguments that will be used to identify and correlate the beginning and end of a single event
          items:
            $ref: '#/components/schemas/MethodArgument'
    MethodArgument:
      type: object
      required:
        - argumentPath
        - argumentType
      properties:
        argumentPath:
          type: string
        argumentType:
          type: string
          enum:
            - TARGET
            - METHOD
    MethodArgumentCriteria:
      type: object
      required:
        - argumentPath
        - argumentType
        - argumentValueMatchPattern
      properties:
        argumentPath:
          type: string
        argumentValueMatchPattern:
          type: string
        argumentType:
          type: string
          enum:
            - TARGET
            - METHOD
            - RETURN_OBJECT
            -
    EventBoundary:
      type: object
      required:
        - eventName
        - boundaryEpoch
        - boundaryThread
      properties:
        eventName:
          type: string
        boundaryEpoch:
          type: integer
          format: int64
        boundaryThread:
          type: string
        boundaryThreadId:
          type: integer
          format: int64
        processId:
          type: integer
          format: int64
        boundaryType:
          type: string
          enum:
            - START
            - END
        eventId:
          type: string
        traceId:
          type: string

    Event:
      type: object
      required:
        - eventName
        - eventStartEpoch
        - eventEndEpoch
      properties:
        processId:
          type: integer
          format: int64
        threadName:
          type: string
        threadId:
          type: integer
          format: int64
        eventName:
          type: string
        eventId:
          type: string
        traceId:
          type: string
        eventStartEpoch:
          type: integer
          format: int64
        eventEndEpoch:
          type: integer
          format: int64

    ChromeTraceCompleteEvent:
      description: "This is based on the spec https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview"
      type: object
      required:
        - name
        - pid
        - tid
        - ph
      properties:
        name:
          description: The event name
          type: string
        cat:
          description: The event category
          type: string
        ph:
          description: This will have the constant value X, aka CompleteEvents
          type: string
        ts:
          type: integer
          format: int64
        pid:
          type: integer
          format: int64
        tid:
          type: string
        args:
          $ref: '#/components/schemas/ChromeTraceEventArgs'
        dur:
          type: integer
          format: int64

    ChromeTraceEventArgs:
      properties:
        threadName:
          type: string
        eventId:
          type: string
        traceId:
          type: string

    SinkConfiguration:
      type: object
      required:
        - objectType
      discriminator:
        propertyName: objectType
      properties:
        objectType:
          type: string

    FileSystemSinkConfig:
      allOf:
        - $ref: '#/components/schemas/SinkConfiguration'
      type: object
      required:
        - path
        - chunkSize
      properties:
        chunkSize:
          type: integer
          default: 100
          format: int32
        path:
          type: string
        filePrefix:
          type: string

    AWSCloudWatchLogGroupSinkConfig:
      allOf:
        - $ref: '#/components/schemas/SinkConfiguration'
      type: object
      required:
        - logGroupArn
        - chunkSize
      properties:
        chunkSize:
          type: integer
          format: int32
          default: 100
        logGroupArn:
          type: string
        logStreamPrefix:
          type: string
